<a href="https://colab.research.google.com/github/Samriddhacoderho/Sleep-Health-Daily-Performance/blob/main/sleep_health_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install opendatasets

Collecting opendatasets
  Downloading opendatasets-0.1.22-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from opendatasets) (4.67.3)
Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (from opendatasets) (2.0.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from opendatasets) (8.3.1)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (6.3.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.15 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (0.1.16)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (26.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.32.4)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle->opendatasets) (0.5.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle->opendatasets) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle->opendatasets) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle->opendatasets) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle->opendatasets) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle->opendatasets) (2026.2.25)
Downloading opendatasets-0.1.22-py3-none-any.whl (15 kB)
Installing collected packages: opendatasets
Successfully installed opendatasets-0.1.22

In [4]:
import opendatasets as od

od.download('https://www.kaggle.com/datasets/mohankrishnathalla/sleep-health-and-daily-performance-dataset')

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: samriddharajsatyal
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/mohankrishnathalla/sleep-health-and-daily-performance-dataset
Downloading sleep-health-and-daily-performance-dataset.zip to ./sleep-health-and-daily-performance-dataset

100%|██████████| 4.07M/4.07M [00:00<00:00, 5.27MB/s]

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/sleep-health-and-daily-performance-dataset/sleep_health_dataset.csv')

In [6]:
df.head()

,person_id,age,gender,occupation,bmi,country,sleep_duration_hrs,sleep_quality_score,rem_percentage,deep_sleep_percentage,...,heart_rate_resting_bpm,sleep_aid_used,shift_work,room_temperature_celsius,weekend_sleep_diff_hrs,season,day_type,cognitive_performance_score,sleep_disorder_risk,felt_rested
0,1,29,Female,Driver,25.7,Japan,6.19,6.6,22.5,19.3,...,63,0,0,20.1,1.84,Autumn,Weekday,73.4,Healthy,0
1,2,55,Female,Software Engineer,22.0,USA,8.32,6.9,26.9,14.9,...,52,1,0,18.0,0.13,Winter,Weekend,99.4,Healthy,1
2,3,42,Male,Nurse,25.0,India,3.74,1.0,20.2,16.2,...,72,0,1,17.9,1.67,Spring,Weekend,2.5,Severe,0
3,4,37,Female,Student,29.5,India,6.79,6.4,17.7,17.7,...,71,0,0,19.1,2.37,Summer,Weekend,67.8,Healthy,0
4,5,23,Male,Lawyer,23.6,Spain,5.02,3.2,23.3,18.3,...,71,0,0,19.7,1.26,Summer,Weekday,38.1,Mild,0

In [7]:
df.shape

(100000, 32)

In [8]:
df.describe()

,person_id,age,bmi,sleep_duration_hrs,sleep_quality_score,rem_percentage,deep_sleep_percentage,sleep_latency_mins,wake_episodes_per_night,caffeine_mg_before_bed,...,nap_duration_mins,stress_score,work_hours_that_day,heart_rate_resting_bpm,sleep_aid_used,shift_work,room_temperature_celsius,weekend_sleep_diff_hrs,cognitive_performance_score,felt_rested
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,...,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,50000.500000,34.706870,26.289673,6.423986,4.871144,20.243968,20.253375,19.836810,3.346610,38.849500,...,14.936840,5.733285,7.134059,66.57017,0.561610,0.084420,20.538093,1.200634,59.227295,0.390120
std,28867.657797,11.036373,4.479578,1.274627,1.506517,3.411354,4.251096,7.584343,1.920877,69.395818,...,21.387567,1.619194,3.482878,7.22821,0.496192,0.278018,2.897565,0.786667,22.249665,0.487779
min,1.000000,18.000000,16.000000,3.000000,1.000000,10.000000,5.000000,1.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,45.00000,0.000000,0.000000,15.000000,-1.000000,0.000000,0.000000
25%,25000.750000,26.000000,23.200000,5.530000,3.800000,18.000000,17.400000,14.000000,2.000000,0.000000,...,0.000000,4.800000,4.700000,62.00000,0.000000,0.000000,18.500000,0.670000,44.200000,0.000000
50%,50000.500000,33.000000,26.300000,6.360000,4.900000,20.300000,20.300000,19.000000,3.000000,0.000000,...,0.000000,5.800000,7.400000,67.00000,1.000000,0.000000,20.500000,1.200000,60.400000,0.000000
75%,75000.250000,42.000000,29.300000,7.270000,6.000000,22.600000,23.200000,25.000000,5.000000,80.000000,...,30.000000,6.800000,9.700000,71.00000,1.000000,0.000000,22.500000,1.740000,75.800000,1.000000
max,100000.000000,69.000000,45.000000,10.500000,10.000000,30.000000,30.000000,58.000000,8.000000,400.000000,...,116.000000,10.000000,18.000000,99.00000,1.000000,1.000000,28.000000,3.000000,100.000000,1.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 32 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   person_id                    100000 non-null  int64
 1   age                          100000 non-null  int64
 2   gender                       100000 non-null  object
 3   occupation                   100000 non-null  object
 4   bmi                          100000 non-null  float64
 5   country                      100000 non-null  object
 6   sleep_duration_hrs           100000 non-null  float64
 7   sleep_quality_score          100000 non-null  float64
 8   rem_percentage               100000 non-null  float64
 9   deep_sleep_percentage        100000 non-null  float64
 10  sleep_latency_mins           100000 non-null  int64
 11  wake_episodes_per_night      100000 non-null  int64
 12  caffeine_mg_before_bed       100000 non-null  int64
 13  alcohol_units_before_bed     100000 non-null  float64
 14  screen_time_before_bed_mins  100000 non-null  int64
 15  exercise_day                 100000 non-null  int64
 16  steps_that_day               100000 non-null  int64
 17  nap_duration_mins            100000 non-null  int64
 18  stress_score                 100000 non-null  float64
 19  work_hours_that_day          100000 non-null  float64
 20  chronotype                   100000 non-null  object
 21  mental_health_condition      100000 non-null  object
 22  heart_rate_resting_bpm       100000 non-null  int64
 23  sleep_aid_used               100000 non-null  int64
 24  shift_work                   100000 non-null  int64
 25  room_temperature_celsius     100000 non-null  float64
 26  weekend_sleep_diff_hrs       100000 non-null  float64
 27  season                       100000 non-null  object
 28  day_type                     100000 non-null  object
 29  cognitive_performance_score  100000 non-null  float64
 30  sleep_disorder_risk          100000 non-null  object
 31  felt_rested                  100000 non-null  int64
dtypes: float64(11), int64(13), object(8)
memory usage: 24.4+ MB

In [10]:
X=df.drop(['sleep_disorder_risk','person_id'],axis=1)
y=df['sleep_disorder_risk']

In [11]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 30 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   age                          100000 non-null  int64
 1   gender                       100000 non-null  object
 2   occupation                   100000 non-null  object
 3   bmi                          100000 non-null  float64
 4   country                      100000 non-null  object
 5   sleep_duration_hrs           100000 non-null  float64
 6   sleep_quality_score          100000 non-null  float64
 7   rem_percentage               100000 non-null  float64
 8   deep_sleep_percentage        100000 non-null  float64
 9   sleep_latency_mins           100000 non-null  int64
 10  wake_episodes_per_night      100000 non-null  int64
 11  caffeine_mg_before_bed       100000 non-null  int64
 12  alcohol_units_before_bed     100000 non-null  float64
 13  screen_time_before_bed_mins  100000 non-null  int64
 14  exercise_day                 100000 non-null  int64
 15  steps_that_day               100000 non-null  int64
 16  nap_duration_mins            100000 non-null  int64
 17  stress_score                 100000 non-null  float64
 18  work_hours_that_day          100000 non-null  float64
 19  chronotype                   100000 non-null  object
 20  mental_health_condition      100000 non-null  object
 21  heart_rate_resting_bpm       100000 non-null  int64
 22  sleep_aid_used               100000 non-null  int64
 23  shift_work                   100000 non-null  int64
 24  room_temperature_celsius     100000 non-null  float64
 25  weekend_sleep_diff_hrs       100000 non-null  float64
 26  season                       100000 non-null  object
 27  day_type                     100000 non-null  object
 28  cognitive_performance_score  100000 non-null  float64
 29  felt_rested                  100000 non-null  int64
dtypes: float64(11), int64(12), object(7)
memory usage: 22.9+ MB

In [12]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.2,stratify=y,random_state=42)

In [13]:
X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((80000, 30), (20000, 30), (80000,), (20000,))

In [14]:
X_train.sample(5)

,age,gender,occupation,bmi,country,sleep_duration_hrs,sleep_quality_score,rem_percentage,deep_sleep_percentage,sleep_latency_mins,...,mental_health_condition,heart_rate_resting_bpm,sleep_aid_used,shift_work,room_temperature_celsius,weekend_sleep_diff_hrs,season,day_type,cognitive_performance_score,felt_rested
12089,35,Other,Student,34.1,Spain,6.07,4.2,19.2,22.3,32,...,Depression,68,0,0,21.9,1.42,Spring,Weekend,57.6,0
5093,22,Male,Software Engineer,29.0,USA,6.82,6.8,24.8,13.1,16,...,Healthy,53,1,0,16.2,2.43,Autumn,Weekday,84.4,1
37720,31,Female,Lawyer,23.0,Japan,3.32,3.3,17.0,18.0,21,...,Depression,68,1,1,22.2,0.61,Spring,Weekday,12.6,0
65327,33,Female,Retired,21.3,USA,8.33,6.4,15.7,19.7,15,...,Healthy,70,1,0,23.6,2.67,Spring,Weekend,68.6,1
12233,25,Male,Nurse,29.1,Japan,3.52,3.1,18.7,20.1,16,...,Anxiety,68,1,1,24.1,2.15,Spring,Weekday,19.5,0

In [15]:
df[df.mental_health_condition=='Both'].sleep_disorder_risk.value_counts()

sleep_disorder_risk
Mild        1978
Severe      1518
Moderate    1362
Healthy      161
Name: count, dtype: int64

In [16]:
from sklearn.compose import ColumnTransformer,make_column_selector
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.pipeline import Pipeline

ordinal_pipeline = Pipeline([
    ('encode', OrdinalEncoder(categories=[['Depression','Both','Anxiety','Healthy']])),
    ('scale', StandardScaler())
])

transformer = ColumnTransformer(transformers=[
    ('ohe', OneHotEncoder(handle_unknown='ignore', sparse_output=False, drop='first'), [1,2,4,19,26,27]),
    ('ordinal', ordinal_pipeline,[20]),
    ('num', StandardScaler(), make_column_selector(dtype_include=['int64', 'float64']))
])

In [17]:
X_train=transformer.fit_transform(X_train)
X_test=transformer.transform(X_test)

In [18]:
X_test

array([[ 0.        ,  0.        ,  0.        , ..., -2.25314939,
         1.12452861,  1.25409764],
       [ 1.        ,  0.        ,  0.        , ...,  0.69711902,
        -0.86295885, -0.79738608],
       [ 0.        ,  0.        ,  0.        , ...,  0.31561879,
        -1.85220601,  1.25409764],
       ...,
       [ 0.        ,  0.        ,  0.        , ..., -0.72714849,
        -0.42679079, -0.79738608],
       [ 0.        ,  0.        ,  0.        , ...,  0.72255236,
        -2.66159004, -0.79738608],
       [ 1.        ,  0.        ,  0.        , ...,  2.0323698 ,
         0.76480238,  1.25409764]])

In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
encoder=LabelEncoder()
Y_train=encoder.fit_transform(Y_train)
Y_test=encoder.transform(Y_test)

In [21]:
import torch
from torch.utils.data import Dataset,DataLoader


class CustomDataSet(Dataset):
  def __init__(self,features,labels):
    self.features=torch.tensor(features,dtype=torch.float32)
    self.labels=torch.tensor(labels,dtype=torch.long)

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,idx):
    return self.features[idx],self.labels[idx]


train_set=CustomDataSet(X_train,Y_train)
test_set=CustomDataSet(X_test,Y_test)

train_loader=DataLoader(train_set,batch_size=64,shuffle=True)
test_loader=DataLoader(test_set,batch_size=64,shuffle=False)

In [22]:
import torch.nn as nn
import torch.optim as optim

In [23]:
#Model Creation

class ANNModel(nn.Module):
  def __init__(self,input_features,output_features):
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(input_features,128),
        nn.ReLU(),
        nn.Linear(128,64),
        nn.ReLU(),
        nn.Linear(64,32),
        nn.ReLU(),
        nn.Linear(32,output_features)
    )

  def forward(self,x):
    return self.network(x)

In [24]:
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda

In [25]:
#Train Loop

model=ANNModel(X_train.shape[1],df['sleep_disorder_risk'].value_counts().shape[0])
model.to(device)
criterion=nn.CrossEntropyLoss()
optimizer=optim.Adam(model.parameters(),lr=0.001)


for i in range(50):
  tot_loss=0
  for x,y in train_loader:
    x=x.to(device)
    y=y.to(device)
    y_pred=model(x)
    loss=criterion(y_pred,y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    tot_loss+=loss.item()
  print(f'Epoch {i+1}, Avg Loss: {tot_loss/len(train_loader)}')

Epoch 1, Avg Loss: 0.41086089582443236
Epoch 2, Avg Loss: 0.3301505481481552
Epoch 3, Avg Loss: 0.30621757461428645
Epoch 4, Avg Loss: 0.28450314735770227
Epoch 5, Avg Loss: 0.26789431331157687
Epoch 6, Avg Loss: 0.2556402324438095
Epoch 7, Avg Loss: 0.24206720517873764
Epoch 8, Avg Loss: 0.2337371697962284
Epoch 9, Avg Loss: 0.22687235820293428
Epoch 10, Avg Loss: 0.2205050219476223
Epoch 11, Avg Loss: 0.21392165946960448
Epoch 12, Avg Loss: 0.20908748504519462
Epoch 13, Avg Loss: 0.20463197305202485
Epoch 14, Avg Loss: 0.20007573877573012
Epoch 15, Avg Loss: 0.19723409072458745
Epoch 16, Avg Loss: 0.19356480416655542
Epoch 17, Avg Loss: 0.18947018731981516
Epoch 18, Avg Loss: 0.18523247143030167
Epoch 19, Avg Loss: 0.18224711185395717
Epoch 20, Avg Loss: 0.1783702815949917
Epoch 21, Avg Loss: 0.17657765996754168
Epoch 22, Avg Loss: 0.17260069312751294
Epoch 23, Avg Loss: 0.16980864067077636
Epoch 24, Avg Loss: 0.1666192088127136
Epoch 25, Avg Loss: 0.16282936130464076
Epoch 26, Avg Loss: 0.15905350997149945
Epoch 27, Avg Loss: 0.15666569081246853
Epoch 28, Avg Loss: 0.15338684851527215
Epoch 29, Avg Loss: 0.14939797581136227
Epoch 30, Avg Loss: 0.14689846838265658
Epoch 31, Avg Loss: 0.14357643866091965
Epoch 32, Avg Loss: 0.1405161436676979
Epoch 33, Avg Loss: 0.13879143721163273
Epoch 34, Avg Loss: 0.1370777295306325
Epoch 35, Avg Loss: 0.13241387865394355
Epoch 36, Avg Loss: 0.1318786544367671
Epoch 37, Avg Loss: 0.12705013616383076
Epoch 38, Avg Loss: 0.12653420074880123
Epoch 39, Avg Loss: 0.12308856577128172
Epoch 40, Avg Loss: 0.1213319868221879
Epoch 41, Avg Loss: 0.11997872741818429
Epoch 42, Avg Loss: 0.11765628957003355
Epoch 43, Avg Loss: 0.11566031516939401
Epoch 44, Avg Loss: 0.11416993123292923
Epoch 45, Avg Loss: 0.1117605910167098
Epoch 46, Avg Loss: 0.10947322967648507
Epoch 47, Avg Loss: 0.10754087354838848
Epoch 48, Avg Loss: 0.10540956849306822
Epoch 49, Avg Loss: 0.10344112924188376
Epoch 50, Avg Loss: 0.10148868752792478

In [26]:
model.eval()

ANNModel(
  (network): Sequential(
    (0): Linear(in_features=57, out_features=128, bias=True)
    (1): ReLU()
    (2): Linear(in_features=128, out_features=64, bias=True)
    (3): ReLU()
    (4): Linear(in_features=64, out_features=32, bias=True)
    (5): ReLU()
    (6): Linear(in_features=32, out_features=4, bias=True)
  )
)

In [28]:
total=0
correct=0
with torch.no_grad():
  for x,y in test_loader:
    x=x.to(device)
    y=y.to(device)
    y_pred=model(x)
    _,predicted=torch.max(y_pred,1)
    total=total+y.shape[0]
    correct=correct+(predicted==y).sum().item()
print(f'Accuracy: {correct/total}')

Accuracy: 0.88435